---
- name: Install and configure elasticsearch
  become: yes
  become_method: sudo
  hosts: all
  remote_user: elastic
  tasks:
    - name: Add elasticsearch pgp key
      apt_key: url=http://packages.elastic.co/GPG-KEY-elasticsearch state=present

    - name: Add package list
      shell: echo "deb http://packages.elastic.co/elasticsearch/2.x/debian stable main" > /etc/apt/sources.list.d/elasticsearch-2.x.list

    - name: Ensure apt-get is updated
      apt: update_cache=yes

    - name: Install java
      apt: name=openjdk-7-jre-headless state=latest

    - name: Install elasticsearch
      apt: name=elasticsearch state=latest

    - name: Start elasticsearch at run
      service: name=elasticsearch enabled=true

- name: Configuring logging and default
  hosts: all
  remote_user: elastic
  tasks:
    - name: Copy logging configuration
      copy: src=../vars/logging.yml dest=/etc/elasticsearch/logging.yml owner=elasticsearch group=elasticsearch mode=0644

    - name: Copy default configuration
      copy: src=../vars/elasticsearch dest=/etc/default/elasticsearch owner=elasticsearch group=elasticsearch mode=064

- name: Configuring http node
  hosts: elasticsearch-http
  remote_user: elastic
  tasks:
    - name: Copy http configuration
      template: src=../vars/elasticsearch-http.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644

    - name: Copy default configuration
      copy: src=../vars/elasticsearch-big-node dest=/etc/default/elasticsearch owner=elasticsearch group=elasticsearch mode=064

- name: Configuring master node
  hosts: elasticsearch-master
  remote_user: elastic
  tasks:
    - name: Copy master configuration
      template: src=../vars/elasticsearch-master.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644

- name: Configuring data node
  hosts: elasticsearch-data
  remote_user: elastic
  tasks:
    - name: Copy data configuration
      template: src=../vars/elasticsearch-data.yml.j2 dest=/etc/elasticsearch/elasticsearch.yml owner=elasticsearch group=elasticsearch mode=0644

    - name: Copy default configuration
      copy: src=../vars/elasticsearch-big-node dest=/etc/default/elasticsearch owner=elasticsearch group=elasticsearch mode=064

- include: restart-elasticsearch.yml