---
- name: Restart all node
  hosts: all
  remote_user: root
  become: yes
  become_method: sudo
  tasks:
    - name: Restart machine
      shell: sleep 2 && shutdown -r now "Ansible reboot triggered"
      async: 1
      poll: 0
      ignore_errors: true