---
- name: Configure the Timezone
  hosts: all
  remote_user: elastic
  become: yes
  become_method: sudo
  tasks:

    - name: Update Timezone to Asia/Singapore
      copy: content="Asia/Singapore\n" dest=/etc/timezone owner=root group=root mode=0644
      register: timezone

    - name: Reconfigure Timezone Data
      shell: dpkg-reconfigure -f noninteractive tzdata
      when: timezone.changed
