---
- name: Update the systems
  hosts: all
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  remote_user: elastic
  become: yes
  become_method: sudo
  
  tasks:
  - name: Ensure dpkg is working properly
    command: dpkg --configure -a

  - name: Clear unmet dependencies
    command: apt-get -f -y install

  - name: Ensure apt-get is updated
    apt: update_cache=yes

  - name: Upgrade the package
    apt: upgrade=full

  - name: Install packages
    apt: name={{item}} state=latest
    with_items:
       - screen
       - curl
       - git
       - vim
       - python-pip
